name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build Idyll Studio
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Add MacOS certs
        if: matrix.os == 'macos-11.0' && startsWith(github.ref, 'refs/tags/')
        run: chmod +x add-osx-cert.sh && ./add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Increase file limits
        if: matrix.os == 'macos-11.0' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo kern.maxfiles=4194304 | sudo tee -a /etc/sysctl.conf
          echo kern.maxfilesperproc=4194304 | sudo tee -a /etc/sysctl.conf
          echo fs.inotify.max_user_watches=4194304 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -w kern.maxfiles=4194304
          sudo sysctl -w kern.maxfilesperproc=4194304
          sudo ulimit -n 524288 unlimited
          sudo launchctl limit maxfiles 4194304 unlimited

      - name: Install dependencies
        if: matrix.os != 'windows-latest'
        run: sudo npm i

      - name: Install dependencies
        if: matrix.os == 'windows-latest'
        run: npm i

      - name: Prune node modules
        if: matrix.os == 'macos-11.0' && startsWith(github.ref, 'refs/tags/')
        run: sudo npm run clean-modules

      - name: Build
        if: matrix.os == 'macos-11.0'
        run: |
          echo kern.maxfiles=4194304 | sudo tee -a /etc/sysctl.conf
          echo kern.maxfilesperproc=4194304 | sudo tee -a /etc/sysctl.conf
          echo fs.inotify.max_user_watches=4194304 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -w kern.maxfiles=4194304
          sudo sysctl -w kern.maxfilesperproc=4194304
          sudo ulimit -n 524288 unlimited
          sudo launchctl limit maxfiles 4194304 unlimited
          sudo npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Build
        if: matrix.os == 'linux-latest'
        run: sudo npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Build
        if: matrix.os == 'windows-latest'
        run: npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/**/idyll-studio*.zip
            out/**/idyll-studio*.dmg
            out/**/idyll-studio*.deb
            out/**/idyll-studio*.rpm
            out/**/idyll-studio*Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
