name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build Idyll Studio
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Add MacOS certs
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: chmod +x add-osx-cert.sh && ./add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.CERTIFICATE_OSX_APPLICATION }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Increase file limits
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
          echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -w kern.maxfiles=65536
          sudo sysctl -w kern.maxfilesperproc=65536
          ulimit -n 65536 65536
          echo "ulimit -n 65536 65536" >> .bashrc
          source .bashrc

      - name: Install dependencies
        run: npm i

      - name: Prune node modules
        if: matrix.os == 'macos-latest' && startsWith(github.ref, 'refs/tags/')
        run: npm run clean-modules

      - name: Build
        run: npm run make
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/**/idyll-studio*.zip
            out/**/idyll-studio*.dmg
            out/**/idyll-studio*.deb
            out/**/idyll-studio*.rpm
            out/**/idyll-studio*Setup.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
