name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build Data Writer
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run make

      - name: Upload builds to release
        uses: softprops/action-gh-release@v1
        with:
          files: out/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
